"""user add UserMixin

Revision ID: 10d71993e15e
Revises: 29affd6c4664
Create Date: 2016-10-27 13:18:43.118000

"""

# revision identifiers, used by Alembic.
revision = '10d71993e15e'
down_revision = '29affd6c4664'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
