"""empty message

Revision ID: 1f68a58dde9
Revises: 268072be9ab2
Create Date: 2016-10-27 16:43:00.170000

"""

# revision identifiers, used by Alembic.
revision = '1f68a58dde9'
down_revision = '268072be9ab2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('country')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index('ix_user_country', 'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_country', 'user', ['country'], unique=1)
    op.drop_index('ix_user_email', 'user')
    op.add_column('user', sa.Column('country', sa.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
