"""remove School table

Revision ID: 29affd6c4664
Revises: 44b20a200446
Create Date: 2016-10-26 17:14:57.547000

"""

# revision identifiers, used by Alembic.
revision = '29affd6c4664'
down_revision = '44b20a200446'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
