"""inital migration

Revision ID: 35d5ec394607
Revises: None
Create Date: 2016-10-26 13:25:26.491000

"""

# revision identifiers, used by Alembic.
revision = '35d5ec394607'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
