"""user add country

Revision ID: 4ca3be6af9ed
Revises: 542d08d75228
Create Date: 2016-10-26 13:37:47.187000

"""

# revision identifiers, used by Alembic.
revision = '4ca3be6af9ed'
down_revision = '542d08d75228'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sa.String(length=64), nullable=True))
    op.create_index('ix_user_country', 'user', ['country'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_country', 'user')
    op.drop_column('user', 'country')
    ### end Alembic commands ###
