"""add post

Revision ID: 542d08d75228
Revises: 35d5ec394607
Create Date: 2016-10-26 13:32:15.053000

"""

# revision identifiers, used by Alembic.
revision = '542d08d75228'
down_revision = '35d5ec394607'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    ### end Alembic commands ###
